language: java
jdk:
  - oraclejdk9
branches:
  only:
    - master
    - develop
dist: trusty
notifications:
  email:
    recipients:
      - esetcat@gmail.com
script:
  #Test unitario y de integracion con cobertura (jacoco)
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify

  #SONARCLOUD
  - mvn sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.marcelocattani=miw-upm-github -Dsonar.login=$SONAR