language: java
jdk:
  - oraclejdk9
branches:
  only:
    - master
    - develop
dist: trusty
notifications:
  email:
    recipients:
      - esetcat@gmail.com

script:
  - mvn verify
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn sonar:sonar -Dsonar.organization=miw-upm-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR